#!/bin/sh
# entrypoint.sh — Generates config/config.toml from environment variables
# and starts the OpenManus API server.
#
# ─── Required environment variables ──────────────────────────────────────────
#   GEMINI_API_KEY   — Google Gemini API key (used for Ideation, QC, and Vision)
#
# ─── Optional environment variables ──────────────────────────────────────────
#   ANTHROPIC_API_KEY — Anthropic API key  (Stage 1.2 Emotional Filter)
#   OPENAI_API_KEY    — OpenAI API key     (Stage 5  Engagement replies)
#
# ─── Pipeline stage → model mapping ──────────────────────────────────────────
#   Stage 1.1  Ideation          gemini-2.5-pro-preview-06-05   (main [llm])
#   Stage 1.2  Emotional Filter  claude-sonnet-4-5               ([llm.emotional_filter])
#   Stage 2.x  Media generation  Wan 2.2 / Fish Speech / LivePortrait / Whisper
#              (SaladCloud GPU workers — not configured here)
#   Stage 3    QC Agent          gemini-2.0-flash                ([llm.qc_agent])
#   Stage 4    Post Agent        Ayrshare API                    (external service)
#   Stage 5    Engagement        gpt-4o-mini                     ([llm.engagement])
#   Stage 6    Feedback Loop     OpenManus Analytics             (reads [llm] default)
#   Vision     Visual analysis   gemini-2.0-flash-exp            ([llm.vision])
# ─────────────────────────────────────────────────────────────────────────────

set -e

GEMINI_API_KEY="${GEMINI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"

GOOGLE_BASE_URL="https://generativelanguage.googleapis.com/v1beta/openai/"
ANTHROPIC_BASE_URL="https://api.anthropic.com/v1/"
OPENAI_BASE_URL="https://api.openai.com/v1/"

mkdir -p config

cat > config/config.toml << TOML
# ============================================================
# OpenManus — Video Production Pipeline Configuration
# Auto-generated by entrypoint.sh at container start-up.
# Do NOT edit this file directly; set environment variables
# and restart the container instead.
# ============================================================

# ────────────────────────────────────────────────────────────
# Stage 1.1 — Ideation (main / default LLM)
# Scrapes trends, generates 5,000 raw hooks/concepts.
# Model: Gemini 2.5 Pro (latest reasoning-capable Gemini 3-era model)
# ────────────────────────────────────────────────────────────
[llm]
model       = "gemini-2.5-pro-preview-06-05"
base_url    = "${GOOGLE_BASE_URL}"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 8192
temperature = 0.7

# ────────────────────────────────────────────────────────────
# Stage 1.2 — Emotional Filter
# Selects top 1,000 ideas scored on Deep Nostalgia / Awe.
# Model: Claude Sonnet 4.5 (Anthropic)
# Requires: ANTHROPIC_API_KEY
# ────────────────────────────────────────────────────────────
[llm.emotional_filter]
model       = "claude-sonnet-4-5"
base_url    = "${ANTHROPIC_BASE_URL}"
api_key     = "${ANTHROPIC_API_KEY}"
max_tokens  = 8192
temperature = 0.5

# ────────────────────────────────────────────────────────────
# Stage 3 — QC Agent
# Watches each render; checks for logos, glitches, audio-sync.
# Model: Gemini 2.0 Flash (fast, low-cost quality checks)
# ────────────────────────────────────────────────────────────
[llm.qc_agent]
model       = "gemini-2.0-flash"
base_url    = "${GOOGLE_BASE_URL}"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 4096
temperature = 0.0

# ────────────────────────────────────────────────────────────
# Stage 5 — Engagement
# Fast, human-vibe replies to comments (monitored for bot patterns).
# Model: GPT-4o Mini (OpenAI) — cheap, conversational, low-latency
# Requires: OPENAI_API_KEY
# ────────────────────────────────────────────────────────────
[llm.engagement]
model       = "gpt-4o-mini"
base_url    = "${OPENAI_BASE_URL}"
api_key     = "${OPENAI_API_KEY}"
max_tokens  = 1024
temperature = 0.9

# ────────────────────────────────────────────────────────────
# Vision — Visual analysis (used by QC Agent and browser tools)
# Model: Gemini 2.0 Flash Exp (multimodal, frame-level inspection)
# ────────────────────────────────────────────────────────────
[llm.vision]
model       = "gemini-2.0-flash-exp"
base_url    = "${GOOGLE_BASE_URL}"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 8192
temperature = 0.0

# ────────────────────────────────────────────────────────────
# Stage 2.x — Media generation (SaladCloud GPU workers)
# These stages run on external GPU infrastructure, NOT via LLM API:
#   Stage 2.1  Visual Base  — Wan 2.2 (MoE) on RTX 4090s
#   Stage 2.2  TTS          — Fish Speech (open-source voice cloning)
#   Stage 2.3  Lip-Sync     — LivePortrait (optimised, 95% cheaper than D-ID)
#   Stage 2.4  Subtitles    — Whisper v3 + FFmpeg (hardcoded subtitle burn)
# Configure SaladCloud endpoints via SALAD_API_KEY / SALAD_ORG_NAME env vars.
# ────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────
# Stage 4 — Post Agent
# Handles TikTok, Instagram, and YouTube API handshakes.
# Configured via AYRSHARE_API_KEY environment variable.
# ────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────
# MCP (Model Context Protocol)
# ────────────────────────────────────────────────────────────
[mcp]
server_reference = "app.mcp.server"

# ────────────────────────────────────────────────────────────
# Run-flow settings
# ────────────────────────────────────────────────────────────
[runflow]
use_data_analysis_agent = false
TOML

echo "config/config.toml written successfully."

exec uvicorn api:app --host 0.0.0.0 --port "${PORT:-8000}"
