#!/bin/bash
set -e

# Entrypoint script for OpenManus on Railway
# Generates config/config.toml from environment variables before starting the app.
#
# LLM stage assignments:
#   Stage 1 (Ideation)          — Gemini 2.5 Pro   [llm] / [llm.vision]
#   Stage 3 (Emotional filter)  — Claude Sonnet 4.5 [llm.filter]
#   Stage 5 (Engagement)        — Gemini 3 Flash    [llm.engagement]

CONFIG_FILE="config/config.toml"
mkdir -p config

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by entrypoint.sh — do not edit manually.

# ── Stage 1 & 2: Ideation — Gemini 2.5 Pro ──────────────────────────────────
[llm]
model       = "gemini-2.5-pro"
base_url    = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 8192
temperature = 0.7

[llm.vision]
model       = "gemini-2.5-pro"
base_url    = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 8192
temperature = 0.7

# ── Stage 3: Emotional filter — Claude Sonnet 4.5 ────────────────────────────
[llm.filter]
model       = "claude-sonnet-4-5"
base_url    = "https://api.anthropic.com/v1/"
api_key     = "${CLAUDE_API_KEY}"
max_tokens  = 8192
temperature = 0.5

# ── Stage 5: Engagement — Gemini 3 Flash ─────────────────────────────────────
# Fast and cost-effective for generating human-vibe comment replies.
[llm.engagement]
model       = "gemini-3-flash"
base_url    = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key     = "${GEMINI_API_KEY}"
max_tokens  = 4096
temperature = 0.9

[mcp]
server_reference = "app.mcp.server"
EOF

echo "✓ Config written to ${CONFIG_FILE}"

# Ensure the Playwright Chromium browser is available for the WebBrowser tool.
# This is a no-op if the browser was already installed during the Docker build.
echo "→ Installing Playwright Chromium browser..."
playwright install chromium
echo "✓ Playwright Chromium ready"

exec python -m uvicorn api:app --host 0.0.0.0 --port "${PORT:-8000}"
